/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.graywizard123.tgbot;

import com.github.graywizard123.tgbot.gui.SceneManager;
import com.github.graywizard123.tgbot.telegram.TelegramManager;
import javafx.application.Application;
import javafx.stage.Stage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App extends Application {

    public static final Logger LOGGER = LoggerFactory.getLogger("TGBot");

    public static void main(String[] args) {
        TelegramManager.start();
        SceneManager.init();
        launch();
    }

    @Override
    public void start(Stage primaryStage) {
        SceneManager.setPrimaryStage(primaryStage);
        SceneManager.setScene("main");
        primaryStage.show();
    }

    @Override
    public void stop() {
        System.exit(0);
    }
}
