/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.graywizard123.tgbot;

import javafx.application.Application;
import javafx.stage.Stage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App extends Application {

    public static final Logger LOGGER = LoggerFactory.getLogger("TGBot");

    public static void main(String[] args) {

        launch();
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

    }
}
